// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GlideController from "./glide_controller"
application.register("glide", GlideController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HireFormController from "./hire_form_controller"
application.register("hire-form", HireFormController)

import StarFormController from "./star_form_controller"
application.register("star-form", StarFormController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)
